/** Multi-sig vectors generated by the official Python SDK (scripts/gen_multisig_vectors.py). */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import type { Address } from "../../src/identity.ts";
import {
	buildEnvelope,
	bytesToHex,
	envelopeDigest,
	innerDigest,
	normaliseSig,
	type PlainObject,
	type Proposal,
	parseEnvelope,
	recoverInnerSigner,
	signEnvelope,
	signProposal,
	trimSig,
	viemSigner,
} from "../../src/index.ts";
import { parseJson, toPlain } from "../../src/json.ts";
import { ACCOUNTS, ADDRESSES } from "./_helpers.ts";

const here = dirname(fileURLToPath(import.meta.url));
const raw = readFileSync(
	join(
		here,
		"..",
		"..",
		"fixtures",
		"signing",
		"python-sdk-multisig-vectors.json",
	),
	"utf8",
);
const data = toPlain(parseJson(raw)) as {
	pythonSdkVersion: string;
	addresses: Record<string, string>;
	vectors: Record<string, unknown>[];
};
const accountOf = (address: string) =>
	ACCOUNTS[ADDRESSES.indexOf(address as Address)] as NonNullable<
		(typeof ACCOUNTS)[number]
	>;

describe(`python-sdk multi-sig vectors (hyperliquid-python-sdk ${data.pythonSdkVersion})`, () => {
	expect(data.addresses.treasury).toBe(ADDRESSES[0]);
	expect(data.addresses.A).toBe(ADDRESSES[1]);
	for (const v of data.vectors) {
		const name = `${v.name as string} [${v.network as string}]`;
		if (v.kind === "envelope") {
			it(`${name}: envelope hash, digest and leader signature`, async () => {
				const parsed = parseEnvelope(v.request);
				expect(parsed.issues.filter((i) => i.severity === "error")).toEqual([]);
				const req = parsed.request as NonNullable<typeof parsed.request>;
				const d = envelopeDigest(req, v.network as "mainnet" | "testnet");
				expect(d.actionHash).toBe(v.actionHash);
				expect(d.digest).toBe(v.digest);
				const sig = v.signature as {
					signer: string;
					r: string;
					s: string;
					v: number;
				};
				expect(sig.signer).toBe(req.action.payload.outerSigner);
				expect(
					await recoverInnerSigner(
						d.digest as `0x${string}`,
						normaliseSig(sig).sig as never,
					),
				).toBe(sig.signer);
				const ours = await signEnvelope(
					req,
					v.network as "mainnet" | "testnet",
					viemSigner(accountOf(sig.signer)),
				);
				expect(trimSig(ours.signature as never)).toEqual(
					trimSig(normaliseSig(sig).sig as never),
				);
			});
			continue;
		}
		it(`${name}: inner digest and every signer`, async () => {
			const payload = {
				network: v.network as "mainnet" | "testnet",
				multiSigUser: v.multiSigUser as Address,
				outerSigner: v.outerSigner as Address,
				action: v.action as PlainObject,
				nonce: v.nonce as number,
				vaultAddress: (v.vaultAddress ?? null) as Address | null,
				expiresAfter: (v.expiresAfter ?? null) as number | null,
			};
			const d = innerDigest(payload);
			expect(d.kind).toBe(v.kind);
			expect(d.digest).toBe(v.digest);
			if (v.kind === "l1") {
				expect(d.l1?.connectionId).toBe(v.connectionId);
				expect(bytesToHex(d.l1?.actionBytes as Uint8Array)).toBe(v.msgpackHex);
			} else {
				expect(d.typedData?.primaryType).toBe(v.primaryType);
			}
			const proposal: Proposal = {
				v: 1,
				payload,
				digest: d.digest as `0x${string}`,
				signatures: [],
				meta: {
					kind: v.kind as "l1" | "user-signed",
					title: null,
					note: null,
					createdBy: null,
					createdAt: null,
					supersedes: null,
					policyAtCreation: null,
				},
				receipt: null,
			};
			for (const s of v.signatures as {
				signer: string;
				r: string;
				s: string;
				v: number;
			}[]) {
				const sig = normaliseSig(s).sig as NonNullable<
					ReturnType<typeof normaliseSig>["sig"]
				>;
				expect(await recoverInnerSigner(d.digest as `0x${string}`, sig)).toBe(
					s.signer,
				);
				const ours = await signProposal(
					proposal,
					viemSigner(accountOf(s.signer)),
				);
				expect(ours.signature?.signer).toBe(s.signer);
				expect(trimSig(ours.signature as never)).toEqual(trimSig(sig));
			}
			// and the envelope our builder produces hashes like the SDK's (checked by the matching envelope vector)
			const built = buildEnvelope(
				{
					...proposal,
					signatures: (
						v.signatures as {
							signer: string;
							r: string;
							s: string;
							v: number;
						}[]
					).map((s) => ({
						...(normaliseSig(s).sig as never as {
							r: `0x${string}`;
							s: `0x${string}`;
							v: 27 | 28;
						}),
						signer: s.signer as Address,
						at: null,
					})),
				},
				{ signatureChainId: "0x66eee" },
			);
			const twin = data.vectors.find(
				(x) =>
					x.name === `${v.name as string} [envelope]` &&
					x.network === v.network,
			) as Record<string, unknown>;
			expect(
				envelopeDigest(built.request, v.network as "mainnet" | "testnet")
					.actionHash,
			).toBe(twin.actionHash);
		});
	}
});
