"""Generate src/samples/signing.ts from fixtures/signing/python-sdk-vectors.json."""
import json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((root / "fixtures/signing/python-sdk-vectors.json").read_text())
PICK = [
    ("order", "order ETH Gtc", "mainnet", "Order (limit Gtc)", "L1 order from the Python SDK's published test vector."),
    ("bracket", "bracket order with builder + expiresAfter", "mainnet", "Bracket order + builder fee + expiresAfter", "Entry with TP/SL children (normalTpsl), a builder fee and expiresAfter."),
    ("cancel", "cancel", "mainnet", "Cancel", "Cancel by oid."),
    ("vault-order", "vault order", "mainnet", "Order on behalf of a vault", "L1 order signed by the master with vaultAddress set."),
    ("usdSend", "usdSend testnet", "testnet", "usdSend", "User-signed USDC transfer (Python SDK published vector, testnet)."),
    ("approveAgent", "approveAgent named", "mainnet", "approveAgent", "User-signed approval of a named API wallet."),
    ("approveBuilderFee", "approveBuilderFee", "mainnet", "approveBuilderFee", "User-signed builder fee approval."),
    ("usdClassTransfer", "usdClassTransfer", "mainnet", "usdClassTransfer", "User-signed spot ⇄ perp transfer."),
]
out = []
for sid, name, net, label, desc in PICK:
    v = next(x for x in data["vectors"] if x["name"] == name and x["network"] == net)
    body = {"action": v["action"], "nonce": v["nonce"], "signature": v["signature"]}
    if v.get("vaultAddress"): body["vaultAddress"] = v["vaultAddress"]
    if v.get("expiresAfter") is not None: body["expiresAfter"] = v["expiresAfter"]
    out.append({
        "id": sid, "label": label, "description": desc, "network": net,
        "vector": name, "family": v["family"],
        "requestBody": json.dumps(body, indent=2),
        "expectedSigner": v["signer"],
        "digest": v["digest"],
    })
ts = '''// Generated by scripts/gen_signing_samples.py from
// fixtures/signing/python-sdk-vectors.json — do not edit by hand.
import type { Network } from "../network.ts";

export interface SigningSample {
\treadonly id: string;
\treadonly label: string;
\treadonly description: string;
\treadonly network: Network;
\t/** Name of the Python SDK vector this sample comes from. */
\treadonly vector: string;
\treadonly family: "l1" | "user-signed";
\t/** Full exchange request body (action, nonce, signature, …) as JSON text. */
\treadonly requestBody: string;
\treadonly expectedSigner: `0x${string}`;
\treadonly digest: `0x${string}`;
}

export const SIGNING_SAMPLES: readonly SigningSample[] = ''' + json.dumps(out, indent="\t") + ";\n"
(root / "src/samples/signing.ts").write_text(ts)
print(len(out), "samples")
