/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HowToUseRouteImport } from './routes/how-to-use'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as MultisigRouteRouteImport } from './routes/multisig/route'
import { Route as FaucetMinerRouteRouteImport } from './routes/faucet-miner/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MultisigIndexRouteImport } from './routes/multisig/index'
import { Route as FaucetMinerIndexRouteImport } from './routes/faucet-miner/index'
import { Route as ToolsWebsocketRouteImport } from './routes/tools/websocket'
import { Route as ToolsTraceRouteImport } from './routes/tools/trace'
import { Route as ToolsSigningRouteImport } from './routes/tools/signing'
import { Route as ToolsRpcRouteImport } from './routes/tools/rpc'
import { Route as ToolsOrdersRouteImport } from './routes/tools/orders'
import { Route as ToolsMultisigRouteImport } from './routes/tools/multisig'
import { Route as ToolsCorewriterRouteImport } from './routes/tools/corewriter'
import { Route as ToolsAssetsRouteImport } from './routes/tools/assets'
import { Route as MultisigProposeRouteImport } from './routes/multisig/propose'
import { Route as MultisigProposalRouteImport } from './routes/multisig/proposal'
import { Route as FaucetMinerHowToUseRouteImport } from './routes/faucet-miner/how-to-use'

const HowToUseRoute = HowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const MultisigRouteRoute = MultisigRouteRouteImport.update({
  id: '/multisig',
  path: '/multisig',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetMinerRouteRoute = FaucetMinerRouteRouteImport.update({
  id: '/faucet-miner',
  path: '/faucet-miner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MultisigIndexRoute = MultisigIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MultisigRouteRoute,
} as any)
const FaucetMinerIndexRoute = FaucetMinerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FaucetMinerRouteRoute,
} as any)
const ToolsWebsocketRoute = ToolsWebsocketRouteImport.update({
  id: '/tools/websocket',
  path: '/tools/websocket',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTraceRoute = ToolsTraceRouteImport.update({
  id: '/tools/trace',
  path: '/tools/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSigningRoute = ToolsSigningRouteImport.update({
  id: '/tools/signing',
  path: '/tools/signing',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRpcRoute = ToolsRpcRouteImport.update({
  id: '/tools/rpc',
  path: '/tools/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsOrdersRoute = ToolsOrdersRouteImport.update({
  id: '/tools/orders',
  path: '/tools/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMultisigRoute = ToolsMultisigRouteImport.update({
  id: '/tools/multisig',
  path: '/tools/multisig',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCorewriterRoute = ToolsCorewriterRouteImport.update({
  id: '/tools/corewriter',
  path: '/tools/corewriter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAssetsRoute = ToolsAssetsRouteImport.update({
  id: '/tools/assets',
  path: '/tools/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const MultisigProposeRoute = MultisigProposeRouteImport.update({
  id: '/propose',
  path: '/propose',
  getParentRoute: () => MultisigRouteRoute,
} as any)
const MultisigProposalRoute = MultisigProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => MultisigRouteRoute,
} as any)
const FaucetMinerHowToUseRoute = FaucetMinerHowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => FaucetMinerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faucet-miner': typeof FaucetMinerRouteRouteWithChildren
  '/multisig': typeof MultisigRouteRouteWithChildren
  '/changes': typeof ChangesRoute
  '/how-to-use': typeof HowToUseRoute
  '/faucet-miner/how-to-use': typeof FaucetMinerHowToUseRoute
  '/multisig/proposal': typeof MultisigProposalRoute
  '/multisig/propose': typeof MultisigProposeRoute
  '/tools/assets': typeof ToolsAssetsRoute
  '/tools/corewriter': typeof ToolsCorewriterRoute
  '/tools/multisig': typeof ToolsMultisigRoute
  '/tools/orders': typeof ToolsOrdersRoute
  '/tools/rpc': typeof ToolsRpcRoute
  '/tools/signing': typeof ToolsSigningRoute
  '/tools/trace': typeof ToolsTraceRoute
  '/tools/websocket': typeof ToolsWebsocketRoute
  '/faucet-miner/': typeof FaucetMinerIndexRoute
  '/multisig/': typeof MultisigIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changes': typeof ChangesRoute
  '/how-to-use': typeof HowToUseRoute
  '/faucet-miner/how-to-use': typeof FaucetMinerHowToUseRoute
  '/multisig/proposal': typeof MultisigProposalRoute
  '/multisig/propose': typeof MultisigProposeRoute
  '/tools/assets': typeof ToolsAssetsRoute
  '/tools/corewriter': typeof ToolsCorewriterRoute
  '/tools/multisig': typeof ToolsMultisigRoute
  '/tools/orders': typeof ToolsOrdersRoute
  '/tools/rpc': typeof ToolsRpcRoute
  '/tools/signing': typeof ToolsSigningRoute
  '/tools/trace': typeof ToolsTraceRoute
  '/tools/websocket': typeof ToolsWebsocketRoute
  '/faucet-miner': typeof FaucetMinerIndexRoute
  '/multisig': typeof MultisigIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faucet-miner': typeof FaucetMinerRouteRouteWithChildren
  '/multisig': typeof MultisigRouteRouteWithChildren
  '/changes': typeof ChangesRoute
  '/how-to-use': typeof HowToUseRoute
  '/faucet-miner/how-to-use': typeof FaucetMinerHowToUseRoute
  '/multisig/proposal': typeof MultisigProposalRoute
  '/multisig/propose': typeof MultisigProposeRoute
  '/tools/assets': typeof ToolsAssetsRoute
  '/tools/corewriter': typeof ToolsCorewriterRoute
  '/tools/multisig': typeof ToolsMultisigRoute
  '/tools/orders': typeof ToolsOrdersRoute
  '/tools/rpc': typeof ToolsRpcRoute
  '/tools/signing': typeof ToolsSigningRoute
  '/tools/trace': typeof ToolsTraceRoute
  '/tools/websocket': typeof ToolsWebsocketRoute
  '/faucet-miner/': typeof FaucetMinerIndexRoute
  '/multisig/': typeof MultisigIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faucet-miner'
    | '/multisig'
    | '/changes'
    | '/how-to-use'
    | '/faucet-miner/how-to-use'
    | '/multisig/proposal'
    | '/multisig/propose'
    | '/tools/assets'
    | '/tools/corewriter'
    | '/tools/multisig'
    | '/tools/orders'
    | '/tools/rpc'
    | '/tools/signing'
    | '/tools/trace'
    | '/tools/websocket'
    | '/faucet-miner/'
    | '/multisig/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changes'
    | '/how-to-use'
    | '/faucet-miner/how-to-use'
    | '/multisig/proposal'
    | '/multisig/propose'
    | '/tools/assets'
    | '/tools/corewriter'
    | '/tools/multisig'
    | '/tools/orders'
    | '/tools/rpc'
    | '/tools/signing'
    | '/tools/trace'
    | '/tools/websocket'
    | '/faucet-miner'
    | '/multisig'
  id:
    | '__root__'
    | '/'
    | '/faucet-miner'
    | '/multisig'
    | '/changes'
    | '/how-to-use'
    | '/faucet-miner/how-to-use'
    | '/multisig/proposal'
    | '/multisig/propose'
    | '/tools/assets'
    | '/tools/corewriter'
    | '/tools/multisig'
    | '/tools/orders'
    | '/tools/rpc'
    | '/tools/signing'
    | '/tools/trace'
    | '/tools/websocket'
    | '/faucet-miner/'
    | '/multisig/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaucetMinerRouteRoute: typeof FaucetMinerRouteRouteWithChildren
  MultisigRouteRoute: typeof MultisigRouteRouteWithChildren
  ChangesRoute: typeof ChangesRoute
  HowToUseRoute: typeof HowToUseRoute
  ToolsAssetsRoute: typeof ToolsAssetsRoute
  ToolsCorewriterRoute: typeof ToolsCorewriterRoute
  ToolsMultisigRoute: typeof ToolsMultisigRoute
  ToolsOrdersRoute: typeof ToolsOrdersRoute
  ToolsRpcRoute: typeof ToolsRpcRoute
  ToolsSigningRoute: typeof ToolsSigningRoute
  ToolsTraceRoute: typeof ToolsTraceRoute
  ToolsWebsocketRoute: typeof ToolsWebsocketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/how-to-use': {
      id: '/how-to-use'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof HowToUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig': {
      id: '/multisig'
      path: '/multisig'
      fullPath: '/multisig'
      preLoaderRoute: typeof MultisigRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet-miner': {
      id: '/faucet-miner'
      path: '/faucet-miner'
      fullPath: '/faucet-miner'
      preLoaderRoute: typeof FaucetMinerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig/': {
      id: '/multisig/'
      path: '/'
      fullPath: '/multisig/'
      preLoaderRoute: typeof MultisigIndexRouteImport
      parentRoute: typeof MultisigRouteRoute
    }
    '/faucet-miner/': {
      id: '/faucet-miner/'
      path: '/'
      fullPath: '/faucet-miner/'
      preLoaderRoute: typeof FaucetMinerIndexRouteImport
      parentRoute: typeof FaucetMinerRouteRoute
    }
    '/tools/websocket': {
      id: '/tools/websocket'
      path: '/tools/websocket'
      fullPath: '/tools/websocket'
      preLoaderRoute: typeof ToolsWebsocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/trace': {
      id: '/tools/trace'
      path: '/tools/trace'
      fullPath: '/tools/trace'
      preLoaderRoute: typeof ToolsTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/signing': {
      id: '/tools/signing'
      path: '/tools/signing'
      fullPath: '/tools/signing'
      preLoaderRoute: typeof ToolsSigningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/rpc': {
      id: '/tools/rpc'
      path: '/tools/rpc'
      fullPath: '/tools/rpc'
      preLoaderRoute: typeof ToolsRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/orders': {
      id: '/tools/orders'
      path: '/tools/orders'
      fullPath: '/tools/orders'
      preLoaderRoute: typeof ToolsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/multisig': {
      id: '/tools/multisig'
      path: '/tools/multisig'
      fullPath: '/tools/multisig'
      preLoaderRoute: typeof ToolsMultisigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/corewriter': {
      id: '/tools/corewriter'
      path: '/tools/corewriter'
      fullPath: '/tools/corewriter'
      preLoaderRoute: typeof ToolsCorewriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/assets': {
      id: '/tools/assets'
      path: '/tools/assets'
      fullPath: '/tools/assets'
      preLoaderRoute: typeof ToolsAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig/propose': {
      id: '/multisig/propose'
      path: '/propose'
      fullPath: '/multisig/propose'
      preLoaderRoute: typeof MultisigProposeRouteImport
      parentRoute: typeof MultisigRouteRoute
    }
    '/multisig/proposal': {
      id: '/multisig/proposal'
      path: '/proposal'
      fullPath: '/multisig/proposal'
      preLoaderRoute: typeof MultisigProposalRouteImport
      parentRoute: typeof MultisigRouteRoute
    }
    '/faucet-miner/how-to-use': {
      id: '/faucet-miner/how-to-use'
      path: '/how-to-use'
      fullPath: '/faucet-miner/how-to-use'
      preLoaderRoute: typeof FaucetMinerHowToUseRouteImport
      parentRoute: typeof FaucetMinerRouteRoute
    }
  }
}

interface FaucetMinerRouteRouteChildren {
  FaucetMinerHowToUseRoute: typeof FaucetMinerHowToUseRoute
  FaucetMinerIndexRoute: typeof FaucetMinerIndexRoute
}

const FaucetMinerRouteRouteChildren: FaucetMinerRouteRouteChildren = {
  FaucetMinerHowToUseRoute: FaucetMinerHowToUseRoute,
  FaucetMinerIndexRoute: FaucetMinerIndexRoute,
}

const FaucetMinerRouteRouteWithChildren =
  FaucetMinerRouteRoute._addFileChildren(FaucetMinerRouteRouteChildren)

interface MultisigRouteRouteChildren {
  MultisigProposalRoute: typeof MultisigProposalRoute
  MultisigProposeRoute: typeof MultisigProposeRoute
  MultisigIndexRoute: typeof MultisigIndexRoute
}

const MultisigRouteRouteChildren: MultisigRouteRouteChildren = {
  MultisigProposalRoute: MultisigProposalRoute,
  MultisigProposeRoute: MultisigProposeRoute,
  MultisigIndexRoute: MultisigIndexRoute,
}

const MultisigRouteRouteWithChildren = MultisigRouteRoute._addFileChildren(
  MultisigRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaucetMinerRouteRoute: FaucetMinerRouteRouteWithChildren,
  MultisigRouteRoute: MultisigRouteRouteWithChildren,
  ChangesRoute: ChangesRoute,
  HowToUseRoute: HowToUseRoute,
  ToolsAssetsRoute: ToolsAssetsRoute,
  ToolsCorewriterRoute: ToolsCorewriterRoute,
  ToolsMultisigRoute: ToolsMultisigRoute,
  ToolsOrdersRoute: ToolsOrdersRoute,
  ToolsRpcRoute: ToolsRpcRoute,
  ToolsSigningRoute: ToolsSigningRoute,
  ToolsTraceRoute: ToolsTraceRoute,
  ToolsWebsocketRoute: ToolsWebsocketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
