// Generated by scripts/gen_signing_samples.py from
// fixtures/signing/python-sdk-vectors.json — do not edit by hand.
import type { Network } from "../network.ts";

export interface SigningSample {
	readonly id: string;
	readonly label: string;
	readonly description: string;
	readonly network: Network;
	/** Name of the Python SDK vector this sample comes from. */
	readonly vector: string;
	readonly family: "l1" | "user-signed";
	/** Full exchange request body (action, nonce, signature, …) as JSON text. */
	readonly requestBody: string;
	readonly expectedSigner: `0x${string}`;
	readonly digest: `0x${string}`;
}

export const SIGNING_SAMPLES: readonly SigningSample[] = [
	{
		id: "order",
		label: "Order (limit Gtc)",
		description: "L1 order from the Python SDK's published test vector.",
		network: "mainnet",
		vector: "order ETH Gtc",
		family: "l1",
		requestBody:
			'{\n  "action": {\n    "type": "order",\n    "orders": [\n      {\n        "a": 1,\n        "b": true,\n        "p": "100",\n        "s": "100",\n        "r": false,\n        "t": {\n          "limit": {\n            "tif": "Gtc"\n          }\n        }\n      }\n    ],\n    "grouping": "na"\n  },\n  "nonce": 0,\n  "signature": {\n    "r": "0xd65369825a9df5d80099e513cce430311d7d26ddf477f5b3a33d2806b100d78e",\n    "s": "0x2b54116ff64054968aa237c20ca9ff68000f977c93289157748a3162b6ea940e",\n    "v": 28\n  }\n}',
		expectedSigner: "0x14791697260e4c9a71f18484c9f997b308e59325",
		digest:
			"0xa5cfed1f2d7948de30aecacc7fea3c5e05c1e759020e96239847879b906f801e",
	},
	{
		id: "bracket",
		label: "Bracket order + builder fee + expiresAfter",
		description:
			"Entry with TP/SL children (normalTpsl), a builder fee and expiresAfter.",
		network: "mainnet",
		vector: "bracket order with builder + expiresAfter",
		family: "l1",
		requestBody:
			'{\n  "action": {\n    "type": "order",\n    "orders": [\n      {\n        "a": 0,\n        "b": true,\n        "p": "60000",\n        "s": "0.001",\n        "r": false,\n        "t": {\n          "limit": {\n            "tif": "Gtc"\n          }\n        }\n      },\n      {\n        "a": 0,\n        "b": false,\n        "p": "66000",\n        "s": "0.001",\n        "r": true,\n        "t": {\n          "trigger": {\n            "isMarket": true,\n            "triggerPx": "66000",\n            "tpsl": "tp"\n          }\n        }\n      },\n      {\n        "a": 0,\n        "b": false,\n        "p": "57000",\n        "s": "0.001",\n        "r": true,\n        "t": {\n          "trigger": {\n            "isMarket": true,\n            "triggerPx": "57000",\n            "tpsl": "sl"\n          }\n        }\n      }\n    ],\n    "grouping": "normalTpsl",\n    "builder": {\n      "b": "0x8c967e73e7b15087c42a10d344cff4c96d877f1d",\n      "f": 10\n    }\n  },\n  "nonce": 1790000000000,\n  "signature": {\n    "r": "0xfeef5e9ba957b3e59da037da3b87832674267048bbe2f9d89a63e5b1d4b1218f",\n    "s": "0x39a885515818a1b37df606c1cb710bb192dffe332418ede73a5627bd3b3053b6",\n    "v": 28\n  },\n  "expiresAfter": 1790000060000\n}',
		expectedSigner: "0x14791697260e4c9a71f18484c9f997b308e59325",
		digest:
			"0x95dfaa6f9040e26815c634f0d8bf618f09360ebf3b29253cc31fbfa72cf446a8",
	},
	{
		id: "cancel",
		label: "Cancel",
		description: "Cancel by oid.",
		network: "mainnet",
		vector: "cancel",
		family: "l1",
		requestBody:
			'{\n  "action": {\n    "type": "cancel",\n    "cancels": [\n      {\n        "a": 4,\n        "o": 123456789\n      }\n    ]\n  },\n  "nonce": 1790000000000,\n  "signature": {\n    "r": "0x570914140dbe88bd4ef6bfde33be7ff9d48c1b1dc0ad7b0537d1f5e1af83ca23",\n    "s": "0x2beaa4f441aec2022394f5ac39a308663830dd44b021ee9bcebe7e463ad7641b",\n    "v": 28\n  }\n}',
		expectedSigner: "0x14791697260e4c9a71f18484c9f997b308e59325",
		digest:
			"0x9bd558bc3a921f694c42108f301e8421bed3fb097a603ca4f4f3cf717593b0d6",
	},
	{
		id: "vault-order",
		label: "Order on behalf of a vault",
		description: "L1 order signed by the master with vaultAddress set.",
		network: "mainnet",
		vector: "vault order",
		family: "l1",
		requestBody:
			'{\n  "action": {\n    "type": "order",\n    "orders": [\n      {\n        "a": 1,\n        "b": true,\n        "p": "100",\n        "s": "100",\n        "r": false,\n        "t": {\n          "limit": {\n            "tif": "Gtc"\n          }\n        }\n      }\n    ],\n    "grouping": "na"\n  },\n  "nonce": 1790000000000,\n  "signature": {\n    "r": "0xb7703b572d26231df31c173687d86fc089138274370691c6da605fa8b66f2a2",\n    "s": "0x168474272361e3704acd77b9108e5c1b524e855d6e8cba944e22ff0274a2bc98",\n    "v": 28\n  },\n  "vaultAddress": "0xdfc24b077bc1425ad1dea75bcb6f8158e10df303"\n}',
		expectedSigner: "0x14791697260e4c9a71f18484c9f997b308e59325",
		digest:
			"0x60d08d957fd929bec695b280c0d7cf3130d3d10da6d5cd6ffbff55cd7b15df43",
	},
	{
		id: "usdSend",
		label: "usdSend",
		description:
			"User-signed USDC transfer (Python SDK published vector, testnet).",
		network: "testnet",
		vector: "usdSend testnet",
		family: "user-signed",
		requestBody:
			'{\n  "action": {\n    "type": "usdSend",\n    "destination": "0x5e9ee1089755c3435139848e47e6635505d5a13a",\n    "amount": "1",\n    "time": 1687816341423,\n    "signatureChainId": "0x66eee",\n    "hyperliquidChain": "Testnet"\n  },\n  "nonce": 1687816341423,\n  "signature": {\n    "r": "0x637b37dd731507cdd24f46532ca8ba6eec616952c56218baeff04144e4a77073",\n    "s": "0x11a6a24900e6e314136d2592e2f8d502cd89b7c15b198e1bee043c9589f9fad7",\n    "v": 27\n  }\n}',
		expectedSigner: "0x14791697260e4c9a71f18484c9f997b308e59325",
		digest:
			"0xcacf7585cc49ca60c6c5fb3001e226c0ca03c46252c893eea574c78907b7cebe",
	},
	{
		id: "approveAgent",
		label: "approveAgent",
		description: "User-signed approval of a named API wallet.",
		network: "mainnet",
		vector: "approveAgent named",
		family: "user-signed",
		requestBody:
			'{\n  "action": {\n    "type": "approveAgent",\n    "agentAddress": "0x9f5c1a0e1b40e1e7a8ab4f4c8b48d6c6b1ee3a0b",\n    "agentName": "bot-1",\n    "nonce": 1790000000000,\n    "signatureChainId": "0x66eee",\n    "hyperliquidChain": "Mainnet"\n  },\n  "nonce": 1790000000000,\n  "signature": {\n    "r": "0xb65bf1a641f94cef1580b464908c4e91f2b3257c969b76bf704664ae3b4ee85b",\n    "s": "0x84f776ad9b67a7f368f9b70912e652caaf3eea6fec044acfd637dfe95c1b0dc",\n    "v": 27\n  }\n}',
		expectedSigner: "0x14791697260e4c9a71f18484c9f997b308e59325",
		digest:
			"0xe0b14373bfaa1cafe836c1b4749e657265f406ed63ffcc98ec073a52619b79e2",
	},
	{
		id: "approveBuilderFee",
		label: "approveBuilderFee",
		description: "User-signed builder fee approval.",
		network: "mainnet",
		vector: "approveBuilderFee",
		family: "user-signed",
		requestBody:
			'{\n  "action": {\n    "type": "approveBuilderFee",\n    "maxFeeRate": "0.01%",\n    "builder": "0x8c967e73e7b15087c42a10d344cff4c96d877f1d",\n    "nonce": 1790000000000,\n    "signatureChainId": "0x66eee",\n    "hyperliquidChain": "Mainnet"\n  },\n  "nonce": 1790000000000,\n  "signature": {\n    "r": "0xcbcd55ef54d6aadf0fc94b00c67343dd7b701f13072aab7c9b7f9ab5cc3f6cc7",\n    "s": "0x7a2bf7ba3545699086b4a83a64aea99c2dcc5cfe51293ad4673413bea36e6b90",\n    "v": 28\n  }\n}',
		expectedSigner: "0x14791697260e4c9a71f18484c9f997b308e59325",
		digest:
			"0xaa95165b6e5fd2681c1a92e9dd4ad4627d4b0c628d9cb18a7d2318d3caabfbcb",
	},
	{
		id: "usdClassTransfer",
		label: "usdClassTransfer",
		description: "User-signed spot \u21c4 perp transfer.",
		network: "mainnet",
		vector: "usdClassTransfer",
		family: "user-signed",
		requestBody:
			'{\n  "action": {\n    "type": "usdClassTransfer",\n    "amount": "10",\n    "toPerp": true,\n    "nonce": 1790000000000,\n    "signatureChainId": "0x66eee",\n    "hyperliquidChain": "Mainnet"\n  },\n  "nonce": 1790000000000,\n  "signature": {\n    "r": "0x6be6039e613ecfa83fb294dd0a1ca495a862782445d3d0551912bb66046e0f40",\n    "s": "0xc6352218c7e6b9d8cdbac8b0bf6c0816832137cb7bdfb0a5498027e6f1ee0d0",\n    "v": 27\n  }\n}',
		expectedSigner: "0x14791697260e4c9a71f18484c9f997b308e59325",
		digest:
			"0x18a2aec7dd839020493f869934afda2c07baece047d92cffc52e363ca1e6807f",
	},
];
